FROM photon:4.0

ARG APP_USER=dpdk
ARG APP_GROUP=dpdk

# Install only runtime deps
RUN tdnf install -y \
      numactl \
      libpcap \
      libgcc \
      libgcc-atomic \
      shadow \
    && tdnf clean all

# Create dpdk user
RUN groupadd -r ${APP_GROUP} \
 && useradd --no-log-init -r -g ${APP_GROUP} ${APP_USER}
